export const result = {
  config: {
    limit: 10,
    page: 1,
    totalPages: 1,
    totalResults: 6,
    no_of_records: 10,
    type: 'WriteUpListing',
    actions: [],
    columns: [
      {
        header: 'Personal Info',
        children: [
          {
            _id: '687a453e99787b4572c9daaf',
            field: 'employee.full_name',
            header: 'Full Name',
            type: 'dropdown',
            pinned: 'left',
            query: null,
            is_visible: true,
            column_dropdown_value: [
              { _id: '67dcf674effa372827121659', value: 'kamran akmal' },
              { _id: '67dd30193489a38d29fa989f', value: 'zia khan' },
            ],
          },
          {
            field: 'employee.email',
            header: 'Email',
            type: 'string',
            query: null,
            is_visible: true,
          },
          {
            field: 'employee.id',
            header: 'Employee ID',
            type: 'string',
            query: null,
            is_visible: true,
          },
        ],
      },
      {
        _id: '687a4509899787b4572c9daaf',
        field: 'employee.group',
        header: 'Group',
        type: 'dropdown',
        pinned: null,
        query: null,
        is_visible: true,
        column_dropdown_value: [
          { _id: '67dcf674effa372827121659', value: 'kamran akmal' },
          { _id: '67d330193489a38d29fa989f', value: 'zia khan' },
          { _id: '67d530193489a38d29fa989f', value: 'zia khan' },
          { _id: '67d630193489a38d29fa989f', value: 'zia khan' },
          { _id: '67d730193489a38d29fa989f', value: 'zia khan' },
          { _id: '67d830193489a38d29fa989f', value: 'zia khan' },
          { _id: '67d930193489a38d29fa989f', value: 'zia khan' },
        ],
      },
      {
        header: 'Location',
        children: [
          {
            field: 'employee.country',
            header: 'Country',
            type: 'string',
            query: null,
            is_visible: true,
          },
          {
            field: 'employee.state',
            header: 'State',
            type: 'string',
            query: null,
            is_visible: true,
          },
          {
            field: 'employee.city',
            header: 'City',
            type: 'string',
            query: null,
            is_visible: true,
          },
        ],
      },
      {
        header: 'Write-Up Details',
        children: [
          {
            _id: '687a453e99787b4572c9dab0',
            field: 'write_up_type',
            header: 'Type',
            type: 'dropdown',
            is_sortable: true,
            query: null,
            is_visible: true,
            column_data: [
              'earlyout',
              'absent',
              'lateout',
              'lateness',
              'clockin',
              'Misspunchout',
            ],
          },
          {
            _id: '687a453e99787b4572c9dab1',
            field: 'write_up_reason',
            header: 'Reason',
            type: 'string',
            is_sortable: true,
            query: null,
            is_visible: true,
          },
          {
            _id: '687a453e99787b4572c9dab2',
            field: 'created_at',
            header: 'Write Up Date',
            type: 'date',
            is_sortable: true,
            query: null,
            is_visible: true,
          },
        ],
      },
      {
        header: 'Status Info',
        children: [
          {
            _id: '687a453e99787b4572c9dab3',
            field: 'status',
            header: 'Status',
            type: 'dropdown',
            is_sortable: true,
            query: null,
            is_visible: true,
            column_dropdown_value: [
              { id: 1, value: 'accepted' },
              { id: 2, value: 'rejected' },
              { id: 3, value: 'pending' },
            ],
            pinned: 'right',
          },
        ],
      },
      // {
      //   _id: '687a453e99787b4572c9daaf',
      //   field: 'employee.full_name',
      //   header: 'Applicant Name',
      //   type: 'dropdown',
      //   search: null,
      //   is_search_able: false,
      //   query: {
      //     first_condition: null,
      //     second_condition: null,
      //     first_value: null,
      //     second_value: null,
      //     condition: null,
      //     __typename: 'queryType',
      //   },
      // query: null,
      // is_visible: true,
      //   filterValue: null,
      //   is_sortable: false,
      //   column_data: [],
      //   column_dropdown_value: [
      //     {
      //       _id: '67dcf674effa372827121659',
      //       value: 'kamran akmal',
      //       __typename: 'column_dropdown_value',
      //     },
      //     {
      //       _id: '67dd30193489a38d29fa989f',
      //       value: 'zia khan',
      //       __typename: 'column_dropdown_value',
      //     },
      //   ],
      //   __typename: 'listingColumnsType',
      // },
      // {
      //   _id: '687a453e99787b4572c9dab0',
      //   field: 'write_up_type',
      //   header: 'Type',
      //   type: 'dropdown',
      //   search: null,
      //   is_search_able: false,
      //   query: {
      //     first_condition: null,
      //     second_condition: null,
      //     first_value: null,
      //     second_value: null,
      //     condition: null,
      //     __typename: 'queryType',
      //   },
      // query: null,
      // is_visible: true,
      //   filterValue: null,
      //   is_sortable: true,
      //   column_data: [
      //     'earlyout',
      //     'absent',
      //     'lateout',
      //     'lateness',
      //     'clockin',
      //     'Misspunchout',
      //   ],
      //   column_dropdown_value: null,
      //   __typename: 'listingColumnsType',
      // },
      // {
      //   _id: '687a453e99787b4572c9dab1',
      //   field: 'write_up_reason',
      //   header: 'Reason',
      //   type: 'string',
      //   search: null,
      //   is_search_able: false,
      //   query: {
      //     first_condition: null,
      //     second_condition: null,
      //     first_value: null,
      //     second_value: null,
      //     condition: null,
      //     __typename: 'queryType',
      //   },
      // query: null,
      // is_visible: true,
      //   filterValue: null,
      //   is_sortable: true,
      //   column_data: [],
      //   column_dropdown_value: null,
      //   __typename: 'listingColumnsType',
      // },
      // {
      //   _id: '687a453e99787b4572c9dab2',
      //   field: 'created_at',
      //   header: 'Write Up Date',
      //   type: 'date',
      //   search: null,
      //   is_search_able: false,
      //   query: {
      //     first_condition: null,
      //     second_condition: null,
      //     first_value: null,
      //     second_value: null,
      //     condition: null,
      //     __typename: 'queryType',
      //   },
      // query: null,
      // is_visible: true,
      //   filterValue: null,
      //   is_sortable: true,
      //   column_data: [],
      //   column_dropdown_value: null,
      //   __typename: 'listingColumnsType',
      // },
      // {
      //   _id: '687a453e99787b4572c9dab3',
      //   field: 'status',
      //   header: 'Status',
      //   type: 'dropdown',
      //   search: null,
      //   is_search_able: false,
      //   query: {
      //     first_condition: null,
      //     second_condition: null,
      //     first_value: null,
      //     second_value: null,
      //     condition: null,
      //     __typename: 'queryType',
      //   },
      // query: null,
      // is_visible: true,
      //   filterValue: null,
      //   is_sortable: true,
      //   column_data: ['accepted', 'rejected', 'pending'],
      //   column_dropdown_value: null,
      //   __typename: 'listingColumnsType',
      // },
    ],
    filters: [],
    __typename: 'dataTableConfig',
  },
  results: [
    {
      _id: '67dd16cc3489a38d29f9ac6c',
      write_up_type: 'EarlyOut',
      informed_hr: false,
      email: null,
      description: 'test',
      attachments: [],
      accept_assign_schedule: true,
      is_deleted: false,
      created_at: '2025-03-21T07:35:40.945Z',
      status: 'accepted',
      Business: {
        _id: '67c15e62c6d34e38167a5095',
        __typename: 'Business',
      },
      employee: {
        id: '67dcf674effa372827121659',
        full_name: 'kamran akmal',
        __typename: 'User',
      },
      __typename: 'WriteUp',
    },
    {
      _id: '67dd16386b55e8cc62929718',
      write_up_type: 'EarlyOut',
      informed_hr: false,
      email: null,
      description: 'test',
      attachments: [],
      accept_assign_schedule: true,
      is_deleted: false,
      created_at: '2025-03-21T07:33:12.750Z',
      status: 'pending',
      Business: {
        _id: '67c15e62c6d34e38167a5095',
        __typename: 'Business',
      },
      employee: {
        id: '67dcf674effa372827121659',
        full_name: 'kamran akmal',
        __typename: 'User',
      },
      __typename: 'WriteUp',
    },
    {
      _id: '67dd0423effa37282712e8a4',
      write_up_type: 'EarlyOut',
      informed_hr: false,
      email: null,
      description: 'test',
      attachments: [],
      accept_assign_schedule: true,
      is_deleted: false,
      created_at: '2025-03-21T06:16:03.447Z',
      status: 'pending',
      Business: {
        _id: '67c15e62c6d34e38167a5095',
        __typename: 'Business',
      },
      employee: {
        id: '67dcf674effa372827121659',
        full_name: 'kamran akmal',
        __typename: 'User',
      },
      __typename: 'WriteUp',
    },
    {
      _id: '67dd030ceffa37282712de94',
      write_up_type: 'EarlyOut',
      informed_hr: true,
      email: 'SMS',
      description: 'late',
      attachments: [],
      accept_assign_schedule: true,
      is_deleted: false,
      created_at: '2025-03-21T06:11:24.434Z',
      status: 'pending',
      Business: {
        _id: '67c15e62c6d34e38167a5095',
        __typename: 'Business',
      },
      employee: {
        id: '67dcf674effa372827121659',
        full_name: 'kamran akmal',
        __typename: 'User',
      },
      __typename: 'WriteUp',
    },
    {
      _id: '67dd030ceffa37282712de85',
      write_up_type: 'EarlyOut',
      informed_hr: true,
      email: 'SMS',
      description: 'late',
      attachments: [],
      accept_assign_schedule: true,
      is_deleted: false,
      created_at: '2025-03-21T06:11:24.372Z',
      status: 'pending',
      Business: {
        _id: '67c15e62c6d34e38167a5095',
        __typename: 'Business',
      },
      employee: {
        id: '67dcf674effa372827121659',
        full_name: 'kamran akmal',
        __typename: 'User',
      },
      __typename: 'WriteUp',
    },
    {
      _id: '67dd02c6effa37282712de45',
      write_up_type: 'EarlyOut',
      informed_hr: true,
      email: 'SMS',
      description: 'late',
      attachments: [],
      accept_assign_schedule: true,
      is_deleted: false,
      created_at: '2025-03-21T06:10:14.173Z',
      status: 'pending',
      Business: {
        _id: '67c15e62c6d34e38167a5095',
        __typename: 'Business',
      },
      employee: {
        id: '67dcf674effa372827121659',
        full_name: 'kamran akmal',
        __typename: 'User',
      },
      __typename: 'WriteUp',
    },
    {
      _id: '67dd16cc3444a38d29f9ac6c',
      write_up_type: 'EarlyOut',
      informed_hr: false,
      email: null,
      description: 'test',
      attachments: [],
      accept_assign_schedule: true,
      is_deleted: false,
      created_at: '2025-03-21T07:35:40.945Z',
      status: 'accepted',
      Business: {
        _id: '67c15e62c6d34e38167a5095',
        __typename: 'Business',
      },
      employee: {
        id: '67dcf674effa372827121659',
        full_name: 'kamran akmal',
        __typename: 'User',
      },
      __typename: 'WriteUp',
    },
    {
      _id: '67dd16383355e8cc62929718',
      write_up_type: 'EarlyOut',
      informed_hr: false,
      email: null,
      description: 'test',
      attachments: [],
      accept_assign_schedule: true,
      is_deleted: false,
      created_at: '2025-03-21T07:33:12.750Z',
      status: 'pending',
      Business: {
        _id: '67c15e62c6d34e38167a5095',
        __typename: 'Business',
      },
      employee: {
        id: '67dcf674effa372827121659',
        full_name: 'kamran akmal',
        __typename: 'User',
      },
      __typename: 'WriteUp',
    },
    {
      _id: '67dd0773effa37282712e8a4',
      write_up_type: 'EarlyOut',
      informed_hr: false,
      email: null,
      description: 'test',
      attachments: [],
      accept_assign_schedule: true,
      is_deleted: false,
      created_at: '2025-03-21T06:16:03.447Z',
      status: 'pending',
      Business: {
        _id: '67c15e62c6d34e38167a5095',
        __typename: 'Business',
      },
      employee: {
        id: '67dcf674effa372827121659',
        full_name: 'kamran akmal',
        __typename: 'User',
      },
      __typename: 'WriteUp',
    },
    {
      _id: '67dd009ceffa37282712de94',
      write_up_type: 'EarlyOut',
      informed_hr: true,
      email: 'SMS',
      description: 'late',
      attachments: [],
      accept_assign_schedule: true,
      is_deleted: false,
      created_at: '2025-03-21T06:11:24.434Z',
      status: 'pending',
      Business: {
        _id: '67c15e62c6d34e38167a5095',
        __typename: 'Business',
      },
      employee: {
        id: '67dcf674effa372827121659',
        full_name: 'kamran akmal',
        __typename: 'User',
      },
      __typename: 'WriteUp',
    },
    {
      _id: '67dd089ceffa37282712de85',
      write_up_type: 'EarlyOut',
      informed_hr: true,
      email: 'SMS',
      description: 'late',
      attachments: [],
      accept_assign_schedule: true,
      is_deleted: false,
      created_at: '2025-03-21T06:11:24.372Z',
      status: 'pending',
      Business: {
        _id: '67c15e62c6d34e38167a5095',
        __typename: 'Business',
      },
      employee: {
        id: '67dcf674effa372827121659',
        full_name: 'kamran akmal',
        __typename: 'User',
      },
      __typename: 'WriteUp',
    },
    {
      _id: '67dd0096effa37282712de45',
      write_up_type: 'EarlyOut',
      informed_hr: true,
      email: 'SMS',
      description: 'late',
      attachments: [],
      accept_assign_schedule: true,
      is_deleted: false,
      created_at: '2025-03-21T06:10:14.173Z',
      status: 'pending',
      Business: {
        _id: '67c15e62c6d34e38167a5095',
        __typename: 'Business',
      },
      employee: {
        id: '67dcf674effa372827121659',
        full_name: 'kamran akmal',
        __typename: 'User',
      },
      __typename: 'WriteUp',
    },
    {
      _id: '673216383355e8cc62929718',
      write_up_type: 'EarlyOut',
      informed_hr: false,
      email: null,
      description: 'test',
      attachments: [],
      accept_assign_schedule: true,
      is_deleted: false,
      created_at: '2025-03-21T07:33:12.750Z',
      status: 'pending',
      Business: {
        _id: '67c15e62c6d34e38167a5095',
        __typename: 'Business',
      },
      employee: {
        id: '67dcf674effa372827121659',
        full_name: 'kamran akmal',
        __typename: 'User',
      },
      __typename: 'WriteUp',
    },
    {
      _id: '67dd0903effa37282712e8a4',
      write_up_type: 'EarlyOut',
      informed_hr: false,
      email: null,
      description: 'test',
      attachments: [],
      accept_assign_schedule: true,
      is_deleted: false,
      created_at: '2025-03-21T06:16:03.447Z',
      status: 'pending',
      Business: {
        _id: '67c15e62c6d34e38167a5095',
        __typename: 'Business',
      },
      employee: {
        id: '67dcf674effa372827121659',
        full_name: 'kamran akmal',
        __typename: 'User',
      },
      __typename: 'WriteUp',
    },
    {
      _id: '67dd087ceffa37282712de94',
      write_up_type: 'EarlyOut',
      informed_hr: true,
      email: 'SMS',
      description: 'late',
      attachments: [],
      accept_assign_schedule: true,
      is_deleted: false,
      created_at: '2025-03-21T06:11:24.434Z',
      status: 'pending',
      Business: {
        _id: '67c15e62c6d34e38167a5095',
        __typename: 'Business',
      },
      employee: {
        id: '67dcf674effa372827121659',
        full_name: 'kamran akmal',
        __typename: 'User',
      },
      __typename: 'WriteUp',
    },
    {
      _id: '67dd065ceffa37282712de85',
      write_up_type: 'EarlyOut',
      informed_hr: true,
      email: 'SMS',
      description: 'late',
      attachments: [],
      accept_assign_schedule: true,
      is_deleted: false,
      created_at: '2025-03-21T06:11:24.372Z',
      status: 'pending',
      Business: {
        _id: '67c15e62c6d34e38167a5095',
        __typename: 'Business',
      },
      employee: {
        id: '67dcf674effa372827121659',
        full_name: 'kamran akmal',
        __typename: 'User',
      },
      __typename: 'WriteUp',
    },
    {
      _id: '67dd00987ffa37282712de45',
      write_up_type: 'EarlyOut',
      informed_hr: true,
      email: 'SMS',
      description: 'late',
      attachments: [],
      accept_assign_schedule: true,
      is_deleted: false,
      created_at: '2025-03-21T06:10:14.173Z',
      status: 'pending',
      Business: {
        _id: '67c15e62c6d34e38167a5095',
        __typename: 'Business',
      },
      employee: {
        id: '67dcf674effa372827121659',
        full_name: 'kamran akmal',
        __typename: 'User',
      },
      __typename: 'WriteUp',
    },
    {
      _id: '67dd09033ffa37282712e8a4',
      write_up_type: 'EarlyOut',
      informed_hr: false,
      email: null,
      description: 'test',
      attachments: [],
      accept_assign_schedule: true,
      is_deleted: false,
      created_at: '2025-03-21T06:16:03.447Z',
      status: 'pending',
      Business: {
        _id: '67c15e62c6d34e38167a5095',
        __typename: 'Business',
      },
      employee: {
        id: '67dcf674effa372827121659',
        full_name: 'kamran akmal',
        __typename: 'User',
      },
      __typename: 'WriteUp',
    },
    {
      _id: '67dd227ceffa37282712de94',
      write_up_type: 'EarlyOut',
      informed_hr: true,
      email: 'SMS',
      description: 'late',
      attachments: [],
      accept_assign_schedule: true,
      is_deleted: false,
      created_at: '2025-03-21T06:11:24.434Z',
      status: 'pending',
      Business: {
        _id: '67c15e62c6d34e38167a5095',
        __typename: 'Business',
      },
      employee: {
        id: '67dcf674effa372827121659',
        full_name: 'kamran akmal',
        __typename: 'User',
      },
      __typename: 'WriteUp',
    },
    {
      _id: '67d4365ceffa37282712de85',
      write_up_type: 'EarlyOut',
      informed_hr: true,
      email: 'SMS',
      description: 'late',
      attachments: [],
      accept_assign_schedule: true,
      is_deleted: false,
      created_at: '2025-03-21T06:11:24.372Z',
      status: 'pending',
      Business: {
        _id: '67c15e62c6d34e38167a5095',
        __typename: 'Business',
      },
      employee: {
        id: '67dcf674effa372827121659',
        full_name: 'kamran akmal',
        __typename: 'User',
      },
      __typename: 'WriteUp',
    },
    {
      _id: '67d900987ffa37282712de45',
      write_up_type: 'EarlyOut',
      informed_hr: true,
      email: 'SMS',
      description: 'late',
      attachments: [],
      accept_assign_schedule: true,
      is_deleted: false,
      created_at: '2025-03-21T06:10:14.173Z',
      status: 'pending',
      Business: {
        _id: '67c15e62c6d34e38167a5095',
        __typename: 'Business',
      },
      employee: {
        id: '67dcf674effa372827121659',
        full_name: 'kamran akmal',
        __typename: 'User',
      },
      __typename: 'WriteUp',
    },
  ],
  __typename: 'writeUpListDataTable',
};